config/routes.rb
Saas::Application.routes.draw do
  root to: 'plans#new'
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'cancel/cancel', to: 'subscriptions#cancel'
end

app/models/paypal_payment.rb
class PaypalPayment
  def initialize(subscription)
    @subscription = subscription
  end
  
  def checkout_details
    process :checkout_details
  end
  
  def checkout_url(options)
    process(:checkout, options).checkout_url
  end
  
  def make_recurring
    process :request_payment
    process :create_recurring_profile, period: :monthly, frequency: 1, start_at: Time.zone.now
  end
  
private

  def process(action, options = {})
    options = options.reverse_merge(
      token: @subscription.paypal_payment_token,
      payer_id: @subscription.paypal_customer_token,
      description: @subscription.plan.name,
      amount: @subscription.plan.price,
      currency: "USD"
    )
    response = PayPal::Recurring.new(options).send(action)
    raise response.errors.inspect if response.errors.present?
    response
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subscriptions
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan
  validates_presence_of :plan_id
  validates_presence_of :email
  
  attr_accessor :stripe_card_token, :paypal_payment_token
  
  def save_with_payment
    if valid?
      if paypal_payment_token.present?
        save_with_paypal_payment
      else
        #save_with_stripe_payment
      end
    end
  end
  
  def paypal
    PaypalPayment.new(self)
  end
  
  def save_with_paypal_payment
    response = paypal.make_recurring
    self.paypal_recurring_profile_token = response.profile_id
    save!
  end

  #def save_with_stripe_payment
    #customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    #self.stripe_customer_token = customer.id
    #save!
  #rescue Stripe::InvalidRequestError => e
    #logger.error "Stripe error while creating customer: #{e.message}"
    #errors.add :base, "There was a problem with your credit card."
    #false
  #end
  
  def payment_provided?
    stripe_card_token.present? || paypal_payment_token.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.order("price")
  end

  def new
  	@plan = Plan.new
  end

  def create
  	@plan = Plan.new(params[:plan])

  	@plan.save
  	redirect_to plans_path
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    plan = Plan.find(params[:plan_id])
    @subscription = plan.subscriptions.build
    if params[:PayerID]
      @subscription.paypal_customer_token = params[:PayerID]
      @subscription.paypal_payment_token = params[:token]
      @subscription.email = @subscription.paypal.checkout_details.email
    end
  end

  def create
    @subscription = Subscription.new(params[:subscription])
    if @subscription.save_with_payment
      puts "******************************************************"
      puts @subscription.inspect
      puts "******************************************************"
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
  end
  
  def paypal_checkout
    plan = Plan.find(params[:plan_id])
    subscription = plan.subscriptions.build
    redirect_to subscription.paypal.checkout_url(
      return_url: new_subscription_url(:plan_id => plan.id),
      cancel_url: root_url
    )
  end

  def cancel
    response = gateway.cancel_profile("5TULUC2FPQGPQ", :note => 'Payment plan was canceled by user')
    flash[:notice] = 'You have successfully canceled your membership'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppSource - Checkout</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Some Store</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Products" %></li>
            <li><%= link_to "Price List" %></li>
            <li><%= link_to "Contact Us" %></li>
            <li><%= link_to "Cart" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
</body>
</html>

app/views/plans/index.html.erb
<div id="plans">
<h1>Sample</h1>
  <% @plans.each do |plan| %>
    <div class="plan">
      <div class="name"><%= plan.name %></div>
      <div class="details">
        <div class="price">
          <%= number_to_currency plan.price, :precision => 0, :unit => 'PHP' %>
        </div>
        <div class="per_month">per month</div>
        <div class="kisses"><%= plan.kisses %> kisses</div>
        <div class="per_month">per month</div>
        <div class="signup">
          <%= link_to "Sign up", new_subscription_path(:plan_id => plan.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/plans/new.html.erb
<%= form_for @plan do |f| %>

	<%= f.label :name  %>
	<%= f.text_field :name  %>
	<%= f.label :price  %>
	<%= f.text_field :price  %>
	<%= f.label :kisses  %>
	<%= f.text_field :kisses  %>
	<p><%= f.submit "Save", :class => "btn btn-primary" %></p>
<% end %>

app/views/subscriptions/cancel.html.erb
sds

app/views/subscriptions/new.html.erb
<h1>Signing up for "<%= @subscription.plan.name %>"</h1>
<p>Includes <strong><%= @subscription.plan.kisses %> AppSource</strong> for only <strong><%= number_to_currency @subscription.plan.price %></strong> per month!</p>

<%= form_for @subscription do |f| %>
  <% if @subscription.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :plan_id %>
 
  <%= f.hidden_field :paypal_customer_token %>
  <%= f.hidden_field :paypal_payment_token %>

  <% unless @subscription.payment_provided? %>
  <div class="field">
    <%= radio_button_tag :pay_with, :card, true %>
    <%= label_tag :pay_with_card do %>
      <%= image_tag "visa.png" %>
      <%= image_tag "mastercard.png" %>
      <%= image_tag "discover.png" %>
      <%= image_tag "american_express.png" %>
      <%= image_tag "jcb.png" %>
    <% end %>
    <br/>
    <%= radio_button_tag :pay_with, :paypal %>
    <%= label_tag :pay_with_paypal do %>
      <%= image_tag "paypal.png" %>
    <% end %>
  </div>
  <% end %>

  
    <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(plan_id: @subscription.plan_id) %>


  <div id="billing_fields">
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
      
    </div>
    <% if @subscription.payment_provided? %>
      Payment has been provided. Click "Subscribe" to complete the subscription.
    <% else %>
      <div class="field">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_code, "Security Code on Card (CVV)" %>
        <%= text_field_tag :card_code, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_month, "Card Expiration" %>
        <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
      </div>
    <% end %>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <%= f.submit "Subscribe" %>
    </div>
  </div>
<% end %>

app/views/subscriptions/show.html.erb
<div id="subscription">
  <h1>Your Subscription</h1>
  <p>You have signed up for the <strong><%= @subscription.plan.name %></strong> plan which includes <strong><%= @subscription.plan.kisses %> AppSource</strong> for just <strong><%= number_to_currency @subscription.plan.price %></strong> per month!</p>
</div>
<%= link_to "sds", cancel_cancel_path %>